<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0;netstandard2.1</TargetFrameworks>

		<Nullable>enable</Nullable>
		<ImplicitUsings>false</ImplicitUsings>
	</PropertyGroup>

	<!-- Unity-safe settings -->
	<PropertyGroup Condition="'$(TargetFramework)'=='netstandard2.1'">
		<LangVersion>8.0</LangVersion>
	</PropertyGroup>

	<!-- Server (modern) settings -->
	<PropertyGroup Condition="'$(TargetFramework)'=='net9.0'">
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>false</ImplicitUsings>
	</PropertyGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
		<PackageReference Include="TypeGen" Version="7.0.0" />
	</ItemGroup>
	<ItemGroup>
	  <None Remove="tgconfig.json" />
	</ItemGroup>
	<ItemGroup>
	  <Content Include="tgconfig.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

</Project>